# Generated by Django 4.0.3 on 2022-03-10 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='bus_name',
            new_name='FutsalName',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='dest',
            new_name='Grounds',
        ),
        migrations.RemoveField(
            model_name='book',
            name='source',
        ),
    ]
