# Generated by Django 4.0.3 on 2022-03-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_book_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='code',
            field=models.CharField(max_length=5, verbose_name='gpnMm'),
        ),
    ]
