# Generated by Django 4.0.3 on 2022-03-10 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_bus_name_book_futsalname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='busid',
        ),
    ]
