# Generated by Django 4.0.3 on 2022-03-10 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_book_busid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='time',
        ),
    ]
