# Generated by Django 4.0.3 on 2022-03-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_book_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ground',
            name='time',
            field=models.TimeField(),
        ),
    ]
