# Generated by Django 4.0.3 on 2022-03-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_book_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ground',
            name='code',
            field=models.CharField(default='nwhEG', max_length=5),
        ),
        migrations.AlterField(
            model_name='book',
            name='code',
            field=models.CharField(default='WgX0O', max_length=5),
        ),
    ]
