# Generated by Django 4.0.3 on 2022-03-11 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_ground_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ground',
            old_name='nos',
            new_name='gname',
        ),
    ]
