# Generated by Django 4.0.3 on 2022-03-11 06:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_ground_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='time',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
